/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HelloDynamoDb;

import org.junit.Test;
import static org.junit.Assert.*;

public class MoviesCreateTableTest {
    @Test public void testAppHasAGreeting() {
        MoviesCreateTable classUnderTest = new MoviesCreateTable();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
